### ISSUE TITLE
access data

### ISSUE THREAD

**Issue by agramfort** [GauthierPerrod/Recommender-System-for-beers#1]
@fleund @GauthierPerrod @yvalas @machu-picchu how do I access the data to run the test submission?

please add a file like this:

https://github.com/didosidali/bank-marketing/blob/master/download_data.py

to download data without pain or put them directly in the repo.

**Comment by GauthierPerrod** [comment]
Bonjour,

Normalement les données pour le test-run sont directement accessibles sous formes de CSV dans le repo, pour le run total il suffit de dezipper le fichier test_train.zip qui sont dans le repo

**Comment by agramfort** [comment]
ok.
